### ISSUE TITLE
The version/downloads counter?

### ISSUE THREAD

**Issue by karan** [crateio/crate.io#11]
Where can I find the downloads count image and version image. I see them in so many repos here on GH, but cannot find a place where I can setup mine.

**Comment by rubik** [comment]
They link to crate.io but they are not on crate.io.
As you can see in the README of one of my projects:
https://raw.github.com/rubik/radon/master/README.rst

They are from `pypip.in`: https://pypip.in/

**Comment by karan** [comment]
Oh. I did not know that!

Thanks!
