### ISSUE TITLE
Use Shields.io to generate Crate.io download badges

### ISSUE THREAD

**Issue by olivierlacan** [crateio/crate.io#15]
I noticed that you guys are using a badge with a design inspired by the Shields badges I created earlier this year to standardize and harmonize metadata badges. 

I also noticed the badge's text baseline is incorrect, so is the padding:
![image](https://f.cloud.github.com/assets/65950/1598049/00b13320-5322-11e3-8c6a-9c2d44ddeb85.png)

Any chance I could help you fix that? Do you know we built a [Shields service](http://shields.io/) to automatically generate badges? Let me know if I can help.

**Comment by rubik** [comment]
Nice idea, but from what I know PyPI badges are made by https://pypip.in/, so to change that you should contact them.

**Comment by olivierlacan** [comment]
Resolved! 
![image](https://cloud.githubusercontent.com/assets/65950/6228267/f18ecf96-b6a9-11e4-895f-3f28008c3802.png)
